### ISSUE TITLE
NSInvalidArgumentException

### ISSUE THREAD

**Issue by sreejith23** [payu-intrepos/PayUCheckoutPro-iOS#10]
When the application is redirected to payu check out pro sdk, the  app is crashed with following error.

`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArray0 objectForKey:]: unrecognized selector sent to instance 0x7fff8002e970'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20421af6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff204306f7 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   CoreFoundation                      0x00007fff20426036 ___forwarding___ + 1489
	4   CoreFoundation                      0x00007fff20428068 _CF_forwarding_prep_0 + 120
	5   PayUBizCoreKit                      0x000000010c79c17c +[PayUBasePaymentModel prepareArrayForCFFromDict:withDownStaus:withCFKey:withDownKey:] + 271
	6   PayUBizCoreKit                      0x000000010c798768 +[PayUModelNetBanking prepareNBArrayForCFFromDict:withDownStaus:] + 60
	7   PayUBizCoreKit                      0x000000010c7a9005 -[PayUJSONParser getCheckoutDetails:] + 156
	8   PayUBizCoreKit                      0x000000010c7a752c -[PayUJSONParser JSONParserforCheckoutDetails:andOneTapTokenDictionary:apiVersion:withCompletionBlock:] + 285
	9   PayUBizCoreKit                      0x000000010c7aa7c2 __64-[PayUWebServiceResponse getCheckoutDetail:withCompletionBlock:]_block_invoke_2 + 545
	10  PayUBizCoreKit                      0x000000010c7be47d __55-[PayUUtils getWebServiceResponse:withCompletionBlock:]_block_invoke + 234
	11  CFNetwork                           0x00007fff2351b6ca CFNetwork + 34506
	12  CFNetwork                           0x00007fff2352f992 _CFHTTPMessageSetResponseProxyURL + 17344
	13  libdispatch.dylib                   0x000000010cf5a7ec _dispatch_call_block_and_release + 12
	14  libdispatch.dylib                   0x000000010cf5b9c8 _dispatch_client_callout + 8
	15  libdispatch.dylib                   0x000000010cf62296 _dispatch_lane_serial_drain + 796
	16  libdispatch.dylib                   0x000000010cf62f9d _dispatch_lane_invoke + 493
	17  libdispatch.dylib                   0x000000010cf6ede2 _dispatch_workloop_worker_thread + 882
	18  libsystem_pthread.dylib             0x00007fff6116845d _pthread_wqthread + 314
	19  libsystem_pthread.dylib             0x00007fff6116742f start_wqthread + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArray0 objectForKey:]: unrecognized selector sent to instance 0x7fff8002e970'
CoreSimulator 732.18.6 - Device: iPhone 12 Pro Max (6CE78DD5-6A13-4B1F-BD9F-8207173F5D96) - Runtime: iOS 14.4 (18D46) - DeviceType: iPhone 12 Pro Max
terminating with uncaught exception of type NSException`

**Comment by RajvinderPayU** [comment]
Hi @sreejith23, can you drop an email to mobile.integration@payu.in with steps to reproduce?
