### ISSUE TITLE
Hi @RajvinderPayU I am cloning the sample project from  https://github.com/payu-intrepos/PayUCheckoutPro-iOS

### ISSUE THREAD

**Issue by amitmishra0807** [payu-intrepos/PayUCheckoutPro-iOS#12]
Hi @RajvinderPayU I am cloning the sample project from  https://github.com/payu-intrepos/PayUCheckoutPro-iOS
 after pod install and after update setting I am facing two errors given below please provide me solution for this
 
 Xcode  version - 12.5.1
 
 
<img width="793" alt="Screenshot 2021-09-08 at 10 12 35 AM" src="https://user-images.githubusercontent.com/34858434/132447859-39936fa5-5467-4009-979b-f274bf286429.png">
<img width="1099" alt="Screenshot 2021-09-08 at 10 12 46 AM" src="https://user-images.githubusercontent.com/34858434/132447872-de8d0602-c885-4e00-a53e-38ab2a7d7672.png">
<img width="1138" alt="Screenshot 2021-09-08 at 10 12 53 AM" src="https://user-images.githubusercontent.com/34858434/132447880-5b394206-2583-4cd8-ad1d-3bb6be62106c.png">
<img width="958" alt="Screenshot 2021-09-08 at 10 26 39 AM" src="https://user-images.githubusercontent.com/34858434/132448841-74865e2f-3975-4a4a-a509-a472ae6478e7.png">

 
  in above provided solution are not working for me 
  
  
  And there are lots of changes project will run then another issue is crash app at runtime after start and log are - given below-
  
  dyld: Symbol not found: _$s8SocketIO0A8AnyEventC5eventSSvpWvd
  Referenced from: /Users/amit.mishra1/Library/Developer/CoreSimulator/Devices/DFFFF916-CAA1-47F0-9F68-9FBA2668B7C6/data/Containers/Bundle/Application/67B54CB6-3F73-482B-A9EB-D6D375125BB9/CheckoutProSwiftSampleApp.app/Frameworks/PayUUPICoreKit.framework/PayUUPICoreKit
  Expected in: /Users/amit.mishra1/Library/Developer/CoreSimulator/Devices/DFFFF916-CAA1-47F0-9F68-9FBA2668B7C6/data/Containers/Bundle/Application/67B54CB6-3F73-482B-A9EB-D6D375125BB9/CheckoutProSwiftSampleApp.app/Frameworks/SocketIO.framework/SocketIO
 in /Users/amit.mishra1/Library/Developer/CoreSimulator/Devices/DFFFF916-CAA1-47F0-9F68-9FBA2668B7C6/data/Containers/Bundle/Application/67B54CB6-3F73-482B-A9EB-D6D375125BB9/CheckoutProSwiftSampleApp.app/Frameworks/PayUUPICoreKit.framework/PayUUPICoreKit
dyld: launch, loading dependent libraries
DYLD_SHARED_CACHE_DIR=/Users/amit.mishra1/Library/Developer/CoreSimulator/Caches/dyld/20E241/com.apple.CoreSimulator.SimRuntime.iOS-14-5.18E182
DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot
DYLD_LIBRARY_PATH=/Users/amit.mishra1/Library/Developer/Xcode/DerivedData/CheckoutProSwiftSampleApp-hjicaufqwzcbcubywscqkjcehgmu/Build/Products/Debug-iphonesimulator:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platfo

_Originally posted by @amitmishra0807 in https://github.com/payu-intrepos/PayUCheckoutPro-iOS/issues/2#issuecomment-914912093_

**Comment by ShubhGar** [comment]
Can you share your podfile.lock

**Comment by amitmishra0807** [comment]
> Can you share your podfile.lock

sure but how can we share  file type not supported
<img width="505" alt="Screenshot 2021-09-08 at 1 12 10 PM" src="https://user-images.githubusercontent.com/34858434/132467919-934711f9-0c37-4ecc-af75-894553f37ec2.png">

**Comment by ShubhGar** [comment]
please update pod and run pod update. 
if not updated first disintegrate pod: pod disintegrate
then run: pod install --repo-update

**Comment by amitmishra0807** [comment]
> pod install --repo-update
i am removing and update pod it will work
Thanks For your help pod issues solved
