### ISSUE TITLE
crash app some time when run app socketIO issue

### ISSUE THREAD

**Issue by amitmishra0807** [payu-intrepos/PayUCheckoutPro-iOS#13]
@RajvinderPayU please check
xcode - 12.5.1
ios- 14.5

dyld: Library not loaded: @rpath/SocketIO.framework/SocketIO
Referenced from: /Users/amit.mishra1/Library/Developer/CoreSimulator/Devices/DFFFF916-CAA1-47F0-9F68-9FBA2668B7C6/data/Containers/Bundle/Application/C9D1CCE3-8747-4B3B-B348-64DD652AA2D7/CheckoutProSwiftSampleApp.app/CheckoutProSwiftSampleApp
Reason: image not found
dyld: launch, loading dependent libraries
DYLD_SHARED_CACHE_DIR=/Users/amit.mishra1/Library/Developer/CoreSimulator/Caches/dyld/20G95/com.apple.CoreSimulator.SimRuntime.iOS-14-5.18E182
DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot
DYLD_LIBRARY_PATH=/Users/amit.mishra1/Library/Developer/Xcode/DerivedData/CheckoutProSwiftSampleApp-fjukonjfiixfjieuvrgtlrppdkee/Build/Products/Debug-iphonesimulator:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platfor

**Comment by ShubhGar** [comment]
Can you share your podfile please

**Comment by amitmishra0807** [comment]
> Can you share your podfile please

lookinto this

 podfile.lock-----------------------------
 
 PODS:
  - PayUIndia-AssetLibrary (2.3.0)
  - PayUIndia-CheckoutPro (2.5.1):
    - PayUIndia-AssetLibrary (~> 2.3)
    - PayUIndia-CheckoutProBase (~> 2.5)
    - PayUIndia-CrashReporter (~> 1.0)
    - PayUIndia-Custom-Browser (~> 7.0)
    - PayUIndia-NetworkReachability (~> 1.0)
    - PayUIndia-PayUParams (~> 2.0)
    - PayUIndia-PG-SDK (~> 6.2)
    - PayUIndia-UPICore (~> 4.1)
  - PayUIndia-CheckoutProBase (2.5.0):
    - PayUIndia-PayUParams (~> 2.0)
  - PayUIndia-CrashReporter (1.0.0)
  - PayUIndia-Custom-Browser (7.0.0)
  - PayUIndia-Logger (2.0.1)
  - PayUIndia-Networking (2.0.1):
    - PayUIndia-Logger (= 2.0.1)
  - PayUIndia-NetworkReachability (1.0.1)
  - PayUIndia-PayUParams (2.0.1)
  - PayUIndia-PG-SDK (6.2.2):
    - PayUIndia-NetworkReachability (~> 1.0)
    - PayUIndia-PayUParams (~> 2.0)
  - PayUIndia-UPICore (4.1.0):
    - PayUIndia-Networking (~> 2.0)
    - Socket.IO-Client-Swift (= 15.1.0)
  - Socket.IO-Client-Swift (15.1.0):
    - Starscream (~> 3.1)
  - Starscream (3.1.1)

DEPENDENCIES:
  - PayUIndia-CheckoutPro

SPEC REPOS:
  trunk:
    - PayUIndia-AssetLibrary
    - PayUIndia-CheckoutPro
    - PayUIndia-CheckoutProBase
    - PayUIndia-CrashReporter
    - PayUIndia-Custom-Browser
    - PayUIndia-Logger
    - PayUIndia-Networking
    - PayUIndia-NetworkReachability
    - PayUIndia-PayUParams
    - PayUIndia-PG-SDK
    - PayUIndia-UPICore
    - Socket.IO-Client-Swift
    - Starscream

SPEC CHECKSUMS:
  PayUIndia-AssetLibrary: 4c257cf5f2e93c5f8245de7401a1ea635854c311
  PayUIndia-CheckoutPro: 04d21f289d20534a5990eb2c9c627334c2059ab6
  PayUIndia-CheckoutProBase: 5d1f5cea7dc8f6ac3baa8779ea4773e4f62d1ab8
  PayUIndia-CrashReporter: e4e6a68b2a2f59fb826331db0799f0167f596593
  PayUIndia-Custom-Browser: ffa6e718d4617d59680cef8364222ecb77e9e1fb
  PayUIndia-Logger: 818c08ae963753d86ff89682daf3ced672896b1c
  PayUIndia-Networking: 355cde94811c667e1da83aa7ebe0b38e0c918b9f
  PayUIndia-NetworkReachability: 99e69781b3be99d7b713075ab7b73e6d73a153e4
  PayUIndia-PayUParams: 284b80ae30e4f40444fdba7035ab2c0c05fb118b
  PayUIndia-PG-SDK: 7767af9dda4b0dc2cebd3f0ddd4efe3adf472112
  PayUIndia-UPICore: 9e0b3e07ae78225fc611b11a88cc000fc669f52d
  Socket.IO-Client-Swift: 7cb44c0ffb86e158cee32d0642d30ec5fdcf8f61
  Starscream: 4bb2f9942274833f7b4d296a55504dcfc7edb7b0

PODFILE CHECKSUM: 2249146791ad778d86d531dac25ceb92a8513f3f

COCOAPODS: 1.11.2



podfile --------------------------


platform :ios, '10.0'

target 'CheckoutProSwiftSampleApp' do
	use_frameworks!
	pod 'PayUIndia-CheckoutPro'
end

**Comment by ShubhGar** [comment]
<img width="798" alt="Screenshot 2021-09-15 at 6 28 52 PM" src="https://user-images.githubusercontent.com/24808854/133437750-9afc3977-6c4b-4b41-9c90-88d82775ec18.png">
Pl
<img width="956" alt="Screenshot 2021-09-15 at 6 29 04 PM" src="https://user-images.githubusercontent.com/24808854/133437761-893d6d2e-94ed-4aea-a7be-48ea3d747a95.png">
Please add these 2 configuration in build setting  and also update pods.

**Comment by amitmishra0807** [comment]
@ShubhGar 

when i update pod and update recommended setting run below error are come


<img width="1440" alt="Screenshot 2021-09-16 at 11 42 18 AM" src="https://user-images.githubusercontent.com/34858434/133559485-5de54f14-4a36-42aa-82dd-68f6906f2750.png">
<img width="1440" alt="Screenshot 2021-09-16 at 11 42 27 AM" src="https://user-images.githubusercontent.com/34858434/133559513-a1f238fc-cdb7-42d5-adb1-b49b9acbb714.png">
<img width="1440" alt="Screenshot 2021-09-16 at 11 42 34 AM" src="https://user-images.githubusercontent.com/34858434/133559518-da1ae699-a61e-490a-af24-3bfcaa1fb307.png">



And if i update pod and can't apply update recommended setting on pod then no error come why?

<img width="1440" alt="Screenshot 2021-09-16 at 11 46 50 AM" src="https://user-images.githubusercontent.com/34858434/133559769-4033757e-e94c-45ac-8d8c-acd8cc5d0172.png">
<img width="1440" alt="Screenshot 2021-09-16 at 11 46 55 AM" src="https://user-images.githubusercontent.com/34858434/133559784-56576770-7bad-4865-9d10-7843251c87fc.png">

**Comment by ShubhGar** [comment]
Can we schedule a call to check It?

**Comment by amitmishra0807** [comment]
> Can we schedule a call to check It?

sure please

**Comment by ShubhGar** [comment]
https://meet.google.com/fym-cmdm-qve

**Comment by amitmishra0807** [comment]
ok thanks
