### ISSUE TITLE
Unable to run application 

### ISSUE THREAD

**Issue by deadpool9987** [payu-intrepos/PayUCheckoutPro-iOS#18]
Hi

I am getting this following error when I did a pod update 

Failed to build module 'PayUCheckoutProKit' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)'

Please help me out as this is a serious issue and i am on a strict deadline and have a delivery in coming week

**Comment by deadpool9987** [comment]
Hi 

The issue is critical as you guys have build the framework on Xcode 13 even though by enabling module stability but it has ruined the support for xcode 12 and and versions of xcode 12. Please provide us some solutions since we are on deadline and now I am not able to build the app now

**Comment by deadpool9987** [comment]
XCode 13 / Swift 5.5 breaks module stability
After updating to XCode 13, our library no longer works on XCode 12, even though module stability is enabled

The XC12 build fails with the following error:

arm64-apple-ios.swiftinterface:14:8: error: no such module '_Concurrency'
import _Concurrency

failed to build module 'XXXXX' from its module interface; the compiler that produced it, 'Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)'

**Comment by RajvinderPayU** [comment]
@deadpool9987 This is something we don't have control on, read [this thread](https://developer.apple.com/forums/thread/690772?answerId=690246022#690246022) for more info.
 You can do 2 things now,

1. if you want to use current version then please use Xcode 13 (from April 2022, anyways Apple will not allow app release from Xcode 12)
2. Use the last version that was working for you on Xcode 12.

**Comment by rohitrvayuz** [comment]
@deadpool9987 You can try doing he following.

1. pod deintegrate
2. remove the podfile.lock file
3. pod install
4. When building change the iOS target of the PayU pod to 11.0
5. Do not click on 'Apply recommended settings' etc while building.
