### ISSUE TITLE
cannot find Swift declaration for this class

### ISSUE THREAD

**Issue by vkawadia** [payu-intrepos/PayUCheckoutPro-iOS#19]
I am developing a flutter plugin that uses the PayUCheckoutPro-iOS.
but while building I am getting error as :
`PayUIndia-CheckoutProBase/PayUCheckoutProBaseKit.framework/Modules/PayUCheckoutProBaseKit.swiftmodule/armv7-apple-ios.swiftinterface:22:54: error: 'PaymentMode' is unavailable: cannot find Swift declaration for this class
      @objc public var paymentModesOrder: [PayUParamsKit.PaymentMode]?
                                                         ^~~~~~~~~~~
    PayUParamsKit.PaymentMode:2:14: note: 'PaymentMode' has been explicitly marked unavailable here
    public class PaymentMode : NSObject, NSCopying {
                 ^
    /payucheckoutpro/example/build/ios/Release-iphoneos/XCFrameworkIntermediates/PayUIndia-CheckoutProBase/PayUCheckoutProBaseKit.framework/Modules/PayUCheckoutProBaseKit.swiftmodule/armv7-apple-ios.swiftinterface:44:49: error: 'PaymentMode' is unavailable: cannot find Swift declaration for this class
      public var quickPaymentOption: [PayUParamsKit.PaymentMode]?
                                                    ^~~~~~~~~~~
    PayUParamsKit.PaymentMode:2:14: note: 'PaymentMode' has been explicitly marked unavailable here
    public class PaymentMode : NSObject, NSCopying {
    
    PayUIndia-CheckoutProBase/PayUCheckoutProBaseKit.framework/Modules/PayUCheckoutProBaseKit.swiftmodule/armv7-apple-ios.swiftinterface:58:43: error: 'PaymentOption' is unavailable: cannot find Swift declaration for this class
      public var paymentOption: PayUParamsKit.PaymentOption?
                                              ^~~~~~~~~~~~~
    PayUParamsKit.PaymentOption:2:14: note: 'PaymentOption' has been explicitly marked unavailable here
    public class PaymentOption : NSObject {
                 ^
    /payucheckoutpro/example/build/ios/Release-iphoneos/XCFrameworkIntermediates/PayUIndia-CheckoutProBase/PayUCheckoutProBaseKit.framework/Modules/PayUCheckoutProBaseKit.swiftmodule/armv7-apple-ios.swiftinterface:67:67: error: 'CardBinInfo' is unavailable: cannot find Swift declaration for this class
    public typealias GetBinInfoOfCard = (_ cardBinInfo: PayUParamsKit.CardBinInfo?, _ error: Swift.Error?) -> ()
                                                                      ^~~~~~~~~~~
    PayUParamsKit.CardBinInfo:2:14: note: 'CardBinInfo' has been explicitly marked unavailable here
    public class CardBinInfo : NSObject {
                 ^
    /payucheckoutpro/example/build/ios/Release-iphoneos/XCFrameworkIntermediates/PayUIndia-CheckoutProBase/PayUCheckoutProBaseKit.framework/Modules/PayUCheckoutProBaseKit.swiftmodule/armv7-apple-ios.swiftinterface:68:62: error: 'CardBinInfo' is unavailable: cannot find Swift declaration for this class
    public typealias GetBinInfo = (_ cardBinInfo: [PayUParamsKit.CardBinInfo]?, _ error: Swift.Error?) -> ()
                                                                 ^~~~~~~~~~~
    PayUParamsKit.CardBinInfo:2:14: note: 'CardBinInfo' has been explicitly marked unavailable here
    public class CardBinInfo : NSObject {
                 ^`
                 
 Using XCode 13  and swift version as 5

**Comment by AmitPayU** [comment]
@vkawadia , Can you help us with some details?
1. Minimum iOS version?
2. Which version of our SDK are you using?

**Comment by vkawadia** [comment]
I have already imported the same. the below one is the code:
`import Flutter
import UIKit
import PayUCheckoutProKit
import PayUCheckoutProBaseKit
import PayUParamsKit

public class SwiftPayucheckoutproPlugin: NSObject, FlutterPlugin, PayUCheckoutProDelegate {
    var url:String = ""
    var logs = false
    var merchantSalt = ""
    var mainResult:FlutterResult?
    
    public static func register(with registrar: FlutterPluginRegistrar) {
        let channel = FlutterMethodChannel(name: "PayuCheckoutPro", binaryMessenger: registrar.messenger())
        let instance = SwiftPayucheckoutproPlugin()
        registrar.addMethodCallDelegate(instance, channel: channel)
    }

    public func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
        self.mainResult=result
        if(call.method.elementsEqual("doPayment")){
            buildPaymentParams(result: result, args: call.arguments)
        }
    }

    func onPaymentSuccess(response: Any?) {
        print("Payment Successful")
        self.mainResult!(response)
    }

    func onPaymentFailure(response: Any?) {
        print(response ?? "Payment Failed. Something Went Wrong")
        let map:[String:Any] = ["status":"failed","message":response ?? "Something Went Wrong"]
        self.mainResult!(map)
    }

    func onPaymentCancel(isTxnInitiated: Bool) {
        print("Payment Cancelled")
        let map:[String:Any] = ["status":"failed","message":"Payment Cancelled"]
        self.mainResult!(map)
    }

    func onError(_ error: Error?) {
        print(error ?? "Payment Error. Something Went Wrong")
        let map:[String:Any] = ["status":"failed","message":error ?? "Something Went Wrong"]
        self.mainResult!(map)
    }

    func generateHash(for param: DictOfString, onCompletion: @escaping PayUHashGenerationCompletion) {
           let hashStringWithoutSalt = param[HashConstant.hashString] ?? ""
           let hashName = param[HashConstant.hashName] ?? ""
           let hashFetchedFromServer = sha512Hex(string:hashStringWithoutSalt+self.merchantSalt)
           print("hashFetchedFromServer==="+hashFetchedFromServer)
           onCompletion([hashName : hashFetchedFromServer])
    }

    func sha512Hex(string: String) -> String {
        var digest = [UInt8](count: Int(CC_SHA512_DIGEST_LENGTH), repeatedValue: 0)
        if let data = string.dataUsingEncoding(NSUTF8StringEncoding) {
            CC_SHA512(data.bytes, CC_LONG(data.length), &digest)
        }

        var digestHex = ""
        for index in 0..<Int(CC_SHA512_DIGEST_LENGTH) {
            digestHex += String(format: "%02x", digest[index])
        }
        return digestHex
    }

    private func buildPaymentParams(result: @escaping FlutterResult,args:Any?){
//        Storing incoming data into variables

        let argsMap = args as! NSDictionary
        let merchantKey = argsMap["merchantKey"] as String
        let merchantSalt = argsMap["merchantSalt"] as String
        self.merchantSalt = merchantSalt
        let amount = argsMap["amount"] as! String
        let transactionId = argsMap["transactionId"] as String
        let productInfo = argsMap["productInfo"] as String
        let firstName = argsMap["firstName"] as String
        let email = argsMap["email"] as String
        let userCredential = argsMap["userCredential"] as String
        let phone = argsMap["phone"] as String
        let successURL = argsMap["surl"] as! String
        let failureURL = argsMap["furl"] as! String
        let isProduction = argsMap["isProduction"] as! Bool
        let hash1String = merchantKey + "|payment_related_details_for_mobile_sdk|" + userCredential + "|" + merchantSalt as! String
        let hash2String = merchantKey + "|vas_for_mobile_sdk|default|" + merchantSalt  as! String
//        Logging if showLog is true
        if(isProduction){
            print("=====================")
            print("Debug Mode is Enabled")
            print("=====================")
            print("Parameters Passed to the PayUMoneyCheckoutPro SDK")
            print("amount: " + amount)
            print("isProduction: " + isProduction.description)
            print("productInfo: " + productInfo)
            print("merchantKey: " + merchantKey)
            print("Phone: " + phone)
            print("Transaction ID: " + transactionId)
            print("FirstName: " + firstName)
            print("Email: " + email)
            print("sURL: " + successURL)
            print("fURL: " + failureURL)
            print("userCredential: " + userCredential)
        }
        
//         Initating Payment Now
        let paymentParam = PayUPaymentParam(key: merchantKey,
                                    transactionId: transactionId,
                                    amount: amount,
                                    productInfo: productInfo,
                                    firstName: firstName,
                                    email: email,
                                    phone: phone,
                                    surl: successURL,
                                    furl: failureURL,
                                    environment: isProduction ? .production : .test)
//        Optional Field
        paymentParam.userCredential=userCredential
        
//        Additional Fields for SDK
        paymentParam.additionalParam[PaymentParamConstant.udf1] = "udf11"
        paymentParam.additionalParam[PaymentParamConstant.udf2] = "udf22"
        paymentParam.additionalParam[PaymentParamConstant.udf3] = "udf33"
        paymentParam.additionalParam[PaymentParamConstant.udf4] = "udf44"
        paymentParam.additionalParam[PaymentParamConstant.udf5] = "udf55"
        // paymentParam.additionalParam[HashConstant.paymentRelatedDetailForMobileSDK] = sha512Hex(string:hash1String)
        // paymentParam.additionalParam[HashConstant.vasForMobileSDK] = sha512Hex(string:hash2String)

//        UI Configuration
        let config = PayUCheckoutProConfig()
        config.showExitConfirmationOnPaymentScreen = true

//        Starting Payment
        if(isProduction){
         print("Initating Payment")
        }
        PayUCheckoutPro.open(on: UIApplication.getTopViewController()!,paymentParam: paymentParam, config:config, delegate: self)
    }
}

extension UIApplication {

    class func getTopViewController(base: UIViewController? = UIApplication.shared.keyWindow?.rootViewController) -> UIViewController? {

        if let nav = base as? UINavigationController {
            return getTopViewController(base: nav.visibleViewController)

        } else if let tab = base as? UITabBarController, let selected = tab.selectedViewController {
            return getTopViewController(base: selected)

        } else if let presented = base?.presentedViewController {
            return getTopViewController(base: presented)
        }
        return base
    }
}
`

**Comment by ShubhGar** [comment]
Please connect with [mobile.integration@payu.in](mailto:mobile.integration@payu.in)
