### ISSUE TITLE
Apple Swift version Issue

### ISSUE THREAD

**Issue by rai09ash** [payu-intrepos/PayUCheckoutPro-iOS#2]
Failed to build module 'PayUCheckoutProKit' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)'

**Comment by umangarya336** [comment]
Please use our latest version of CheckoutPro v2.0.0 which we released on 7th Oct 2020.

**Comment by tecbharat** [comment]
Failed to build module 'PayUCheckoutProKit' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)'

**Comment by ShubhamJuIT** [comment]
@umangarya336 2.0.0, 2.1.0 and 2.1.1 in all version same issue is coming..

**Comment by ShubhamJuIT** [comment]
@rai09ash did you find any solution

**Comment by sreejith23** [comment]
@umangarya336 Still has the same issue. Did you find any solution?

**Comment by RajvinderPayU** [comment]
@sreejith23  are you facing this issue on simulator? If yes, then please add arm64 in excluded architecture of Debug mode. Our SDKs are supported on Xcode 12.

![excludedArch](https://user-images.githubusercontent.com/32862750/120437052-50ee2c00-c39d-11eb-9462-56fbafb0f314.jpg)

**Comment by sreejith23** [comment]
@RajvinderPayU This issue is resolved. Yes, the issue was on simulator.

**Comment by amitmishra0807** [comment]
Hi @RajvinderPayU I am cloning the sample project from  https://github.com/payu-intrepos/PayUCheckoutPro-iOS
 after pod install and after update setting I am facing two errors given below please provide me solution for this
 
 Xcode  version - 12.5.1
 
 
<img width="793" alt="Screenshot 2021-09-08 at 10 12 35 AM" src="https://user-images.githubusercontent.com/34858434/132447859-39936fa5-5467-4009-979b-f274bf286429.png">
<img width="1099" alt="Screenshot 2021-09-08 at 10 12 46 AM" src="https://user-images.githubusercontent.com/34858434/132447872-de8d0602-c885-4e00-a53e-38ab2a7d7672.png">
<img width="1138" alt="Screenshot 2021-09-08 at 10 12 53 AM" src="https://user-images.githubusercontent.com/34858434/132447880-5b394206-2583-4cd8-ad1d-3bb6be62106c.png">

 
  in above provided solution are not working for me 
  
  
  And there are lots of changes project will run then another issue is crash app at runtime after start and log are - given below-
  
  dyld: Symbol not found: _$s8SocketIO0A8AnyEventC5eventSSvpWvd
  Referenced from: /Users/amit.mishra1/Library/Developer/CoreSimulator/Devices/DFFFF916-CAA1-47F0-9F68-9FBA2668B7C6/data/Containers/Bundle/Application/67B54CB6-3F73-482B-A9EB-D6D375125BB9/CheckoutProSwiftSampleApp.app/Frameworks/PayUUPICoreKit.framework/PayUUPICoreKit
  Expected in: /Users/amit.mishra1/Library/Developer/CoreSimulator/Devices/DFFFF916-CAA1-47F0-9F68-9FBA2668B7C6/data/Containers/Bundle/Application/67B54CB6-3F73-482B-A9EB-D6D375125BB9/CheckoutProSwiftSampleApp.app/Frameworks/SocketIO.framework/SocketIO
 in /Users/amit.mishra1/Library/Developer/CoreSimulator/Devices/DFFFF916-CAA1-47F0-9F68-9FBA2668B7C6/data/Containers/Bundle/Application/67B54CB6-3F73-482B-A9EB-D6D375125BB9/CheckoutProSwiftSampleApp.app/Frameworks/PayUUPICoreKit.framework/PayUUPICoreKit
dyld: launch, loading dependent libraries
DYLD_SHARED_CACHE_DIR=/Users/amit.mishra1/Library/Developer/CoreSimulator/Caches/dyld/20E241/com.apple.CoreSimulator.SimRuntime.iOS-14-5.18E182
DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot
DYLD_LIBRARY_PATH=/Users/amit.mishra1/Library/Developer/Xcode/DerivedData/CheckoutProSwiftSampleApp-hjicaufqwzcbcubywscqkjcehgmu/Build/Products/Debug-iphonesimulator:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platfo
