### ISSUE TITLE
Remove UPI 

### ISSUE THREAD

**Issue by AmodD** [payu-intrepos/PayUCheckoutPro-iOS#20]
Would like to remove UPI from checkout options 

We tried following

`var preferredPaymentModes: [PaymentMode] = []
preferredPaymentModes.append(PaymentMode(paymentType: .ccdc))
preferredPaymentModes.append(PaymentMode(paymentType: .netBanking))
//preferredPaymentModes.append(PaymentMode(paymentType: .upi))
//preferredPaymentModes.append(PaymentMode(paymentType: .wallet))
//preferredPaymentModes.append(PaymentMode(paymentType: .emi))

let config = PayUCheckoutProConfig()
config.paymentModesOrder = preferredPaymentModes`

But it does not work.

- Does PayUCheckoutProConfig  have something other than paymentModesOrder to set preferredPaymentModes ?
- Is paymentModesOrder only for ordering ?

**Comment by RajvinderPayU** [comment]
Hi @AmodD,

It can be disabled from backend, please get in touch with your key account manager or email us on mobile.integration@payu.in.
