### ISSUE TITLE
Getting this error/crash on app launch in Xcode13 for iOS versions below iOS 15. Added as Swift Package Manager. Note: The same error/crash occurs in CheckoutProSwiftSampleApp as well.

### ISSUE THREAD

**Issue by kavinrajec** [payu-intrepos/PayUCheckoutPro-iOS#21]
dyld: Library not loaded: @rpath/SocketIO.framework/SocketIO
  Referenced from: /private/var/containers/Bundle/Application/8F306337-A838-4EF3-99FB-04447115BADA/XXXX.app/Frameworks/PayUCheckoutProKit.framework/PayUCheckoutProKit
  **Reason: Incompatible library version: PayUCheckoutProKit requires version 1.0.0 or later, but SocketIO provides version 0.0.0
dyld: launch, loading dependent libraries**
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib:/usr/lib/libMTLCapture.dylib

**Comment by ShubhGar** [comment]
Which version you add from SPM. Please share the dependencies  downloaded by SPM.

**Comment by kavinrajec** [comment]
@ShubhGar SPM Downloaded Version-4.0.2, attached screenshot
<img width="1680" alt="Screenshot 2022-03-14 at 11 31 00 AM" src="https://user-images.githubusercontent.com/15178135/158114077-178e2a4d-21b3-4f5e-9e32-eeb9500978e9.png">
.
