### ISSUE TITLE
Failed to build module 'PayUCheckoutProKit'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', while this compiler is 'Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)'). Please select a toolchain which matches the SDK.

### ISSUE THREAD

**Issue by tusharquantsapp** [payu-intrepos/PayUCheckoutPro-iOS#22]
I am running XCode 13.0 and I have integrate the pod `PayUIndia-CheckoutPro`

I have tried setting "arm64" in build settings for "Excluded Architectures" for Any iOS Simulator SDK. However I am trying the run the app on real device. I am getting the following error...

`Failed to build module 'PayUCheckoutProKit'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', while this compiler is 'Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)'). Please select a toolchain which matches the SDK.`

<img width="1046" alt="Screenshot 2022-04-19 at 10 40 59 AM" src="https://user-images.githubusercontent.com/44606706/163924510-77a09872-36da-484a-bfc3-4f2c49f8b804.png">

<img width="409" alt="Screenshot 2022-04-19 at 10 41 15 AM" src="https://user-images.githubusercontent.com/44606706/163924527-18380488-42e2-4797-a767-a12f9839af82.png">

**Comment by ShubhGar** [comment]
Please ensure that your minimum deployment target version is 11.0, and then attempt cleaning the derived data in your project. If you want any additional support, please send an email to mobile.integration@payu.in.
