### ISSUE TITLE
Not getting onPaymentFailure() callback if wrong card details are entered

### ISSUE THREAD

**Issue by tusharquantsapp** [payu-intrepos/PayUCheckoutPro-iOS#23]
Is there any way to get callback to `func onPaymentFailure(response: Any?) {}` if wrong card details are entered?

Right now if I enter wrong card details I get the screen where error is shown as follows...

![IMG_0025](https://user-images.githubusercontent.com/44606706/165222138-370edb70-4db9-413d-aaa7-54daf7c453fc.PNG)

But I was expecting to get a callback to `onPaymentFailure()` to notify our server that payment has been failed without PayUCheckoutPro sdk to retry for the payment details as shown below...

![IMG_0026](https://user-images.githubusercontent.com/44606706/165222152-3d27e4b4-e8bc-4d07-a79f-884fc0aced5e.PNG)

**Comment by AmitPayU** [comment]
Yes @tusharquantsapp, we do have that feature.
Please contact to our integration support team at mobile.integration@payu.in for further assistance.

**Comment by tusharquantsapp** [comment]
> 

Okay. Will contact support.
