### ISSUE TITLE
 PayUIndia-Checkoutpro With Swift package manager throws compilation error

### ISSUE THREAD

**Issue by vakhileshwar** [payu-intrepos/PayUCheckoutPro-iOS#24]
Hi Team,

I am integrating PayUIndia-Checkoutpro in my app
Via Xcode - Go to File-> Add Package-> https://github.com/payu-intrepos/PayUCheckoutPro-iOS

It throws following error 

**Showing All Messages
Couldn’t update repository submodules:

fatal: No url found for submodule path 'SampleApp/SwiftSampleApp/CheckoutProSwiftSampleApp/checkouts/PayUAnalytics-iOS' in .gitmodules**

And saying resting package graph failed
Am using Xcode 13.2.1

please help me

**Comment by AmitPayU** [comment]
Hi @vakhileshwar ,
Please update your xcode to v 13.3.1 or use cocoapods.

**Comment by vakhileshwar** [comment]
Sorry I am using Xcode 13.2.1 and for some reasons we don't want use cocoapods
Could you please help me

**Comment by AmitPayU** [comment]
Please update your xcode to v 13.3.1 or later

**Comment by vakhileshwar** [comment]
Hi @AmitPayU 
I updated my Xcode to 13.4.1 and added checkout pro Via Xcode - Go to File-> Add Package-> https://github.com/payu-intrepos/PayUCheckoutPro-iOS

Still issue is the same , and we don't want to use cocoa pods in my project

**Comment by AmitPayU** [comment]
Please drop your query to mobile.integration@payu.in
Thanks

**Comment by vakhileshwar** [comment]
Thank you and updated SDK is working fine @AmitPayU
