### ISSUE TITLE
Failed to build module 'PayUCheckoutProKit'; 

### ISSUE THREAD

**Issue by rahulmehndiratta** [payu-intrepos/PayUCheckoutPro-iOS#26]
Failed to build module 'PayUCheckoutProKit'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)', while this compiler is 'Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)'). Please select a toolchain which matches the SDK.

I am using xcode 13.2

**Comment by ShubhGar** [comment]
Hi, Itsb xcode different swift version issue, please update your xcode version or use swift toolchain.

**Comment by rahulmehndiratta** [comment]
> Hi, It's Xcode different swift version issue, please update your Xcode version or use Swift toolchain.

Can you please describe how to use Swift toolchain?
either share some reference  link

**Comment by rahulmehndiratta** [comment]
I upgrade to xcode 13.4.1 still same issue

Failed to build module 'PayUCheckoutProKit'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)', while this compiler is 'Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)'). Please select a toolchain which matches the SDK.

Either can you tell me xcode exact version.

**Comment by ShubhGar** [comment]
Please connect with [mobile.integration@payu.in](mailto:mobile.integration@payu.in)
