### ISSUE TITLE
'Customer Address' not reflecting on the PayUDashboard

### ISSUE THREAD

**Issue by chintanMaisuriya** [payu-intrepos/PayUCheckoutPro-iOS#29]
We are using  "PayUCheckoutPro-iOS" SDK to get payment from our customers. We require customer's address along with PayUPaymentParam for some internal usage. we are passing the address field as mentioned in the documents (Please refer the attachment). But the "Customer Address" field in the PayUDashboard still showing "--". 

Can anyone help us with this?

<img width="535" alt="Screenshot 2023-12-29 at 1 36 08 PM" src="https://github.com/payu-intrepos/PayUCheckoutPro-iOS/assets/38044758/dfe0d008-38cb-4a14-927c-9c60348f87b4">

**Comment by AmitPayU** [comment]
Hi @chintanMaisuriya , As of now we are not using this model for Checkout PRO. 
If you have any further queries please contact our integration team at mobile.integration@payu.in.
Thanks!
