### ISSUE TITLE
Apple swift version issue facing in Xcode 12.3

### ISSUE THREAD

**Issue by tecbharat** [payu-intrepos/PayUCheckoutPro-iOS#3]
Failed to build module 'PayUCheckoutProKit' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)'

Also not solved through

https://github.com/payu-intrepos/PayUCheckoutPro-iOS/releases/tag/PayUIndia-CheckoutPro_2.0.0

**Comment by ShubhamJuIT** [comment]
I am also facing the same issue
/Users/shubham.mua/Shubham/Github/eko_payu/example/ios/Pods/PayUIndia-UPICore/Dependencies/PayUUPICoreKit.framework/Modules/PayUUPICoreKit.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:8:8: error: compiling for iOS 10.0, but module 'SocketIO' has a minimum deployment target of iOS 12.0: /Users/shubham.mua/Library/Developer/Xcode/DerivedData/Runner-csyxaxvhbjucxfbdxpbrxwdspzab/Build/Products/Debug-iphonesimulator/Socket.IO-Client-Swift/SocketIO.framework/Modules/SocketIO.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
import SocketIO
       ^
/Users/shubham.mua/Shubham/Github/eko_payu/example/ios/Pods/PayUIndia-CheckoutPro/PayUCheckoutProKit/PayUCheckoutProKit.framework/Modules/PayUCheckoutProKit.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:13:8: error: failed to build module 'PayUUPICoreKit' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)'
import PayUUPICoreKit
       ^
/Users/shubham.mua/Shubham/Github/eko_payu/ios/Classes/SwiftEkoPayuPlugin.swift:3:8: error: failed to build module 'PayUCheckoutProKit' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)'
import PayUCheckoutProKit

**Comment by ShubhamJuIT** [comment]
@tecbharat do you find any solution for that.. i even tried with other versions PayUCheckoutPro... Its same in 2.0.0 , 2.1.0 and 2.1.1

**Comment by tecbharat** [comment]
> @tecbharat do you find any solution for that.. i even tried with other versions PayUCheckoutPro... Its same in 2.0.0 , 2.1.0 and 2.1.1

No not till now, I am stuck. Waiting for solution.

**Comment by RishabhSRS** [comment]
Try setting "Socket-IO-Client-Swift" pod
iOS deployment target to iOS: 10.0

also do same for starscream

<img width="787" alt="Screenshot 2021-04-30 at 1 44 28 AM" src="https://user-images.githubusercontent.com/22503174/116613159-fa34a300-a955-11eb-85e0-8a2993376080.png">

**Comment by ShubhamJuIT** [comment]
@RishabhSRS setting to 10.0 solves the problem with socket.io

now this error is coming 
Conformance of 'Reachability.NetworkStatus' to 'Equatable' is unavailable

in this line 
extension PayUCheckoutProKit.Reachability.NetworkStatus : Swift.Hashable {}

**Comment by deadpool9987** [comment]
@ShubhamJuIT Setting to 10.0 does not solves the problem
