### ISSUE TITLE
Stuck on "Processing..."

### ISSUE THREAD

**Issue by tusharquantsapp** [payu-intrepos/PayUCheckoutPro-iOS#31]
I have integrated version 7.6.1 using SPM. The Payment screen is stuck on processing.

![IMG_D3C8932A7DE4-1](https://github.com/payu-intrepos/PayUCheckoutPro-iOS/assets/44606706/6e5e7ca5-f7fa-40ef-a2f7-80da2320c507)

**Comment by AmitPayU** [comment]
Hi @tusharquantsapp , Please connect us our integration support team at [mobile.integration@payu.in]

**Comment by tusharquantsapp** [comment]
It was hash related issue. It's been resolved now.

**Comment by tusharquantsapp** [comment]
It was hash related issue. It's been resolved now.
