### ISSUE TITLE
Bitcode bundle could not be generated

### ISSUE THREAD

**Issue by RishabhSRS** [payu-intrepos/PayUCheckoutPro-iOS#6]
Xcode Version :  12. 4
PayU Version : Latest, just updated 

<img width="1439" alt="Screenshot 2021-04-30 at 3 31 49 AM" src="https://user-images.githubusercontent.com/22503174/116623976-bb5a1980-a964-11eb-87d1-f4a2f33b9600.png">

**Comment by ShubhGar** [comment]
We are already looking into the issue.

**Comment by ShubhGar** [comment]
@RishabhSRS  This issue is fixed, please use version 2.1.1. Thanks
