### ISSUE TITLE
Not able to add dynamic hash. 

### ISSUE THREAD

**Issue by hussainAgharia** [payu-intrepos/PayUCheckoutPro-iOS#7]
Thanks for the whole sample code. but the only issue I am facing is to add hash value(dynamic). even your sample code is giving the error of "Invalid Hash". and I am not able to proceed further.

**error : Optional(Error Domain=com.payu.PayUCheckoutPro Code=9999 "Invalid Hash."**

**Comment by RajvinderPayU** [comment]
@hussainAgharia in our sample code, we have not entered hash calculation locally because hash should be calculated at server side, please fetch the hash from your server, use this [link](https://payumobile.gitbook.io/sdk-integration/android/payucheckoutpro/hash-details) to know more.

**Comment by RajvinderPayU** [comment]
@sreejith23 are you getting this error for UPI payments? If yes, then get in touch with your key account manager, your UPI flags are not properly set for iOS.

**Comment by sreejith23** [comment]
@RajvinderPayU i am receiving this error for PayUCheckoutPro.

**Comment by RajvinderPayU** [comment]
@sreejith23 Seems like there is some issue with the way hash is getting calculated at your server. Reach out to us at mobile.integration@payu.in, we will assist you.

**Comment by EwireAnanthu** [comment]
@RajvinderPayU  following error message got from  PayUCheckoutPro in android.
message = Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
 code =  5014.

**Comment by Rahul-Hooda** [comment]
@EwireAnanthu  - This issue occurs when you are either using test key on Prod environment or vice-versa. Please verify this. If still issue persists then please drop a mail mobile.integration@payu.in for a quick help.

**Comment by rohitrvayuz** [comment]
@RajvinderPayU @hussainAgharia @sreejith23 @EwireAnanthu 



```
Error Domain=com.payu.PayUCheckoutPro Code=9999 "Invalid Hash." UserInfo={NSLocalizedDescription=Invalid Hash.}
Unsupported value: Error Domain=com.payu.PayUCheckoutPro Code=9999 "Invalid Hash." UserInfo={NSLocalizedDescription=Invalid Hash.} of type NSError
```
