### ISSUE TITLE
no support for Swift 5.3 and above.

### ISSUE THREAD

**Issue by kunwar231** [payu-intrepos/PayUCheckoutPro-iOS#8]
Failed to build module 'PayUUPICoreKit' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)'

**Comment by RajvinderPayU** [comment]
@kunwar231 which version are you using?

**Comment by kunwar231** [comment]
I am using 2.1.0

**Comment by kunwar231** [comment]
> @kunwar231 which version are you using?

I am using 2.2.0

**Comment by RajvinderPayU** [comment]
@kunwar231 are you still facing this issue?

**Comment by RajvinderPayU** [comment]
@kunwar231 if you're facing this issue on simulator then use [this link](https://github.com/payu-intrepos/PayUCheckoutPro-iOS/issues/2#issuecomment-852788801) to solve your problem.
