### ISSUE TITLE
Error in xcode 12.5

### ISSUE THREAD

**Issue by ninadmego** [payu-intrepos/PayUCheckoutPro-iOS#9]
I am getting the following error since upgrading xcode to 12.5
"Failed to build module 'PayUCheckoutProKit' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)'"

**Comment by RajvinderPayU** [comment]
Can you try [this](https://github.com/payu-intrepos/PayUCheckoutPro-iOS/issues/2#issuecomment-852788801)?
